### PR TITLE
fix vulnerabilities and improved implementation

### PR DESCRIPTION
**Pull request by FarzeenKist**
## Fixes and Improvements

1. Users could call the withdraw function and drain the smart contract of all its funds
2. There were a few typo issues in your NatSpec comments that were causing compiling issues and you were also using old versions of solidity.
3. Users could mint NFTs without having any wins and I've also noticed that you mentioned that users could only mint if they had 5 or 10 wins in your NatSpec comment yet this wasn't checked.
4. Restructured smart contract to follow the logic and implementation of the project's idea. This also made it possible to implement necessary checks to fix the aforementioned vulnerabilities
5.  I've added new functionalities that would allow a user to start a game, another user could join the specific game by providing the correct **secret phrase** and modified the withdraw function to also end a game with a winner address.
6. It is worth noting that while the secret phrase fixes some vulnerabilities, there is still the issue where one of the two players can maliciously use the secret phrase to declare themselves as the winner. To fix that, you could record each player's plays and then have the logic of deciding the winner implemented onto the smart contract or you could implement another secret phrase that would be provided to only the winner of every game (in this case it would have to be generated by the smart contract or on the UI).

### CODE REVIEW

**Comment by dripthugger** [comment]
3. Users cannot mint NFTs withous wins because of checking it on the server. ExpressJS checks if user have wins over 5 or 10, and checks if user did not mint an nft before. So i thought there is no need to check it in the contract. And there is no need to check if wins_count is 5 or 10, cause it will be hard to add more achievements(will need to recompile contract every time).

**Comment by dripthugger** [comment]
Also you deleted a parameter win_history from withdraw function. This param saves a game history on the blockchain, and this string has a format - XOOOXXXOOO, where the first sign was the sign user played with, the other signs is signs on the board from 1 to 9.
I guess it was not the best solution from me, but yeah

**Comment by FarzeenKist** [comment]
> Also you deleted a parameter win_history from withdraw function. This param saves a game history on the blockchain, and this string has a format - XOOOXXXOOO, where the first sign was the sign user played with, the other signs is signs on the board from 1 to 9. I guess it was not the best solution from me, but yeah

You weren't using the argument or saving it. However, if you would like to implement this method (which would tremendously make the smart contract more secure), this repo might be of some help: https://github.com/schemar/TicTacToe.

**Comment by FarzeenKist** [comment]
> 3. Users cannot mint NFTs without wins because of checking it on the server. ExpressJS checks if the user have wins over 5 or 10, and checks if user did not mint an nft before. So i thought there is no need to check it in the contract. And there is no need to check if wins_count is 5 or 10, cause it will be hard to add more achievements(will need to recompile contract every time).

Users can interact directly with the smart contract, so it's usually best always consider that. It's also best practice to perform necessary checks on the front-end and back-end(in this case, the smart contract and express). As for providing unique NFTs depending on the number of wins(5,10,15), You could use the ERC-1155 standard.

**Pull request merged**
